//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap auditor {
            get {
                object obj = ResourceManager.GetObject("auditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black {
            get {
                object obj = ResourceManager.GetObject("black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bug {
            get {
                object obj = ResourceManager.GetObject("bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cables {
            get {
                object obj = ResourceManager.GetObject("cables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carpet {
            get {
                object obj = ResourceManager.GetObject("carpet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carty {
            get {
                object obj = ResourceManager.GetObject("carty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap darktile {
            get {
                object obj = ResourceManager.GetObject("darktile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap darkwall {
            get {
                object obj = ResourceManager.GetObject("darkwall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desk {
            get {
                object obj = ResourceManager.GetObject("desk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desk2 {
            get {
                object obj = ResourceManager.GetObject("desk2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deskdark {
            get {
                object obj = ResourceManager.GetObject("deskdark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deskevil {
            get {
                object obj = ResourceManager.GetObject("deskevil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deskmed {
            get {
                object obj = ResourceManager.GetObject("deskmed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dummy {
            get {
                object obj = ResourceManager.GetObject("dummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dwight {
            get {
                object obj = ResourceManager.GetObject("dwight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elevatorDown {
            get {
                object obj = ResourceManager.GetObject("elevatorDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elevatorUp {
            get {
                object obj = ResourceManager.GetObject("elevatorUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fancydoor {
            get {
                object obj = ResourceManager.GetObject("fancydoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap frank {
            get {
                object obj = ResourceManager.GetObject("frank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Heroes&gt;
        ///	&lt;Hero id=&quot;1&quot; texture=&quot;milton&quot; name=&quot;Milton&quot;
        ///	      desc=&quot;A master of the incendiary arts, Milton&apos;s talents are oft overlooked due to his poor communication skills and affinity for staplers of the red Swingline variety.&quot;&gt;
        ///		&lt;Attributes stamina=&quot;20&quot; block=&quot;0&quot; combo=&quot;10&quot; /&gt;
        ///		&lt;Item id=&quot;11&quot; /&gt;
        ///		&lt;Item id=&quot;15&quot; /&gt;
        ///		&lt;Item id=&quot;17&quot; /&gt;
        ///
        ///		&lt;Spell id=&quot;2&quot; auto=&quot;true&quot; /&gt;
        ///		&lt;Spell id=&quot;1&quot; /&gt;
        ///		&lt;Spell id=&quot;3&quot; /&gt;
        ///	&lt;/Hero&gt;
        ///
        ///	&lt;Hero id=&quot;2&quot; texture=&quot;stu&quot; name=&quot;Stu  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heroes {
            get {
                return ResourceManager.GetString("Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Items&gt;
        ///	&lt;!--SlotIDs:
        ///	  Weapon,
        ///	  Head,
        ///	  Body,
        ///	  Feet,
        ///  --&gt;
        ///
        ///	&lt;!-- Tier 0--&gt;
        ///
        ///	&lt;Equippable id=&quot;11&quot; name=&quot;Clipboard&quot; slot=&quot;Weapon&quot;&gt;
        ///		&lt;Attributes stamina=&quot;3&quot; block=&quot;2&quot; combo=&quot;5&quot; /&gt;
        ///	&lt;/Equippable&gt;
        ///	&lt;Equippable id=&quot;12&quot; name=&quot;Tattered Band T-shirt&quot; slot=&quot;Body&quot;&gt;
        ///		&lt;Attributes stamina=&quot;2&quot; block=&quot;3&quot; combo=&quot;2&quot; /&gt;
        ///	&lt;/Equippable&gt;
        ///	&lt;Equippable id=&quot;13&quot; name=&quot;Broken Flip Flops&quot; slot=&quot;Feet&quot;&gt;
        ///		&lt;Attributes stamina=&quot;2&quot; block=&quot;1&quot; combo=&quot;3&quot; /&gt;
        ///	&lt;/Equippable&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jamm {
            get {
                object obj = ResourceManager.GetObject("jamm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laggy {
            get {
                object obj = ResourceManager.GetObject("laggy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lawyer {
            get {
                object obj = ResourceManager.GetObject("lawyer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lebowski {
            get {
                object obj = ResourceManager.GetObject("lebowski", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leslie {
            get {
                object obj = ResourceManager.GetObject("leslie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lindsay {
            get {
                object obj = ResourceManager.GetObject("lindsay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;LootPools&gt;
        ///
        ///	&lt;LootPool id=&quot;1&quot;&gt;
        ///		&lt;Item id=&quot;100&quot; chance=&quot;0.1&quot; /&gt;
        ///		&lt;Item id=&quot;112&quot; chance=&quot;0.1&quot; /&gt;
        ///		&lt;Item id=&quot;114&quot; chance=&quot;0.1&quot; /&gt;
        ///		&lt;Item id=&quot;115&quot; chance=&quot;0.1&quot; /&gt;
        ///		&lt;Item id=&quot;116&quot; chance=&quot;0.1&quot; /&gt;
        ///		&lt;Item id=&quot;117&quot; chance=&quot;0.1&quot; /&gt;
        ///	&lt;/LootPool&gt;
        ///
        ///	&lt;LootPool id=&quot;2&quot; limit=&quot;1&quot;&gt;
        ///		&lt;Item id=&quot;11&quot; chance=&quot;1&quot; /&gt;
        ///		&lt;Item id=&quot;12&quot; chance=&quot;1&quot; /&gt;
        ///		&lt;Item id=&quot;14&quot; chance=&quot;1&quot; /&gt;
        ///		&lt;Item id=&quot;15&quot; chance=&quot;1&quot; /&gt;
        ///		&lt;Item id=&quot;16&quot; chance=&quot;1&quot; /&gt;
        ///		&lt;Item id=&quot;17&quot; chance=&quot;1&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LootPools {
            get {
                return ResourceManager.GetString("LootPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lumbergh {
            get {
                object obj = ResourceManager.GetObject("lumbergh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Maps&gt;
        ///	&lt;Map id=&quot;1&quot;&gt;
        ///		&lt;Tiles&gt;
        ///			02 02 02 02 02 02 02 02 02 02 02 02 02
        ///			02 00 02 03 00 00 00 04 02 04 00 00 02
        ///			02 00 02 00 00 00 00 00 02 00 00 00 02
        ///			02 00 02 00 00 00 00 00 02 02 00 02 02
        ///			02 00 00 00 00 00 00 00 00 00 00 00 02
        ///			02 00 00 00 00 00 00 00 00 00 00 00 02
        ///			02 00 00 00 00 00 00 00 00 00 00 00 02
        ///			02 03 00 00 00 00 00 00 00 00 00 00 02
        ///			02 02 02 02 00 00 00 00 00 00 00 00 02
        ///			02 20 00 02 00 00 00 00 00 00 00 00 02
        ///			02  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medbox {
            get {
                object obj = ResourceManager.GetObject("medbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medtile {
            get {
                object obj = ResourceManager.GetObject("medtile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap milton {
            get {
                object obj = ResourceManager.GetObject("milton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Monsters&gt;
        ///
        ///	&lt;Monster id=&quot;3&quot; texture=&quot;dummy&quot; name=&quot;Dummy&quot;&gt;
        ///		&lt;Attributes stamina=&quot;9999999&quot; block=&quot;10&quot; combo=&quot;10&quot; /&gt;
        ///	&lt;/Monster&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///	&lt;Monster id=&quot;4&quot; texture=&quot;deskevil&quot; name=&quot;Cryptolocked Box&quot;&gt;
        ///		&lt;Attributes stamina=&quot;8&quot; block=&quot;10&quot; combo=&quot;400&quot; /&gt;
        ///		&lt;Spell id=&quot;41&quot; /&gt;
        ///		&lt;Spell id=&quot;42&quot; /&gt;
        ///		&lt;LootPool id=&quot;101&quot; /&gt;
        ///		&lt;LootPool id=&quot;150&quot; /&gt;
        ///	&lt;/Monster&gt;
        ///
        ///	&lt;Monster id=&quot;5&quot; texture=&quot;printer&quot; name=&quot;Jammed Printer&quot;&gt;
        ///		&lt;Attributes stamina=&quot;20&quot; block=&quot;50&quot; combo= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plant1 {
            get {
                object obj = ResourceManager.GetObject("plant1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plant2 {
            get {
                object obj = ResourceManager.GetObject("plant2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plant3 {
            get {
                object obj = ResourceManager.GetObject("plant3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plant4 {
            get {
                object obj = ResourceManager.GetObject("plant4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roy {
            get {
                object obj = ResourceManager.GetObject("roy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap serverBase {
            get {
                object obj = ResourceManager.GetObject("serverBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap serverLights {
            get {
                object obj = ResourceManager.GetObject("serverLights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap serverRed {
            get {
                object obj = ResourceManager.GetObject("serverRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shoerner {
            get {
                object obj = ResourceManager.GetObject("shoerner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smallbox {
            get {
                object obj = ResourceManager.GetObject("smallbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Spells&gt;
        ///  &lt;!--Milton--&gt;
        ///  &lt;TargetedDamage id=&quot;1&quot; name=&quot;Mumble&quot; damage=&quot;9&quot; castTime=&quot;2&quot; cooldown=&quot;6&quot;&gt;
        ///    &lt;Auras&gt;
        ///      &lt;Stun duration=&quot;1&quot; blockable=&quot;true&quot; /&gt;
        ///    &lt;/Auras&gt;
        ///  &lt;/TargetedDamage&gt;
        ///
        ///  &lt;TargetedDamage id=&quot;2&quot; name=&quot;Staple Fire&quot; damage=&quot;1&quot; castTime=&quot;0.3&quot; cooldown=&quot;0&quot; /&gt;
        ///
        ///  &lt;AreaDamage id=&quot;3&quot; name=&quot;Incinerate&quot; damage=&quot;5&quot; castTime=&quot;2.5&quot; cooldown=&quot;10&quot;&gt;
        ///    &lt;Auras&gt;
        ///      &lt;DamageOverTime blockable=&quot;false&quot; duration=&quot;6&quot; damage=&quot;15&quot; /&gt;
        ///    &lt;/Auras&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stu {
            get {
                object obj = ResourceManager.GetObject("stu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Tiles&gt;
        ///	&lt;Tile id=&quot;0&quot; texture=&quot;carpet&quot; obstacle=&quot;false&quot; /&gt;
        ///	&lt;Tile id=&quot;1&quot; texture=&quot;lumbergh&quot; obstacle=&quot;false&quot; /&gt;
        ///	&lt;Tile id=&quot;2&quot; texture=&quot;wall&quot; obstacle=&quot;true&quot; /&gt;
        ///	&lt;Tile id=&quot;3&quot; texture=&quot;carpet plant1&quot; obstacle=&quot;true&quot; /&gt;
        ///	&lt;Tile id=&quot;4&quot; texture=&quot;carpet deskmed&quot; obstacle=&quot;true&quot; /&gt;
        ///	&lt;Tile id=&quot;5&quot; texture=&quot;carpet plant2&quot; obstacle=&quot;true&quot; /&gt;
        ///	&lt;Tile id=&quot;6&quot; texture=&quot;carpet plant3&quot; obstacle=&quot;true&quot; /&gt;
        ///	&lt;Tile id=&quot;7&quot; texture=&quot;carpet plant4&quot; obstacle=&quot;true&quot; /&gt;
        ///	&lt;Tile id=&quot;8&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vendo {
            get {
                object obj = ResourceManager.GetObject("vendo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap verydarkwall {
            get {
                object obj = ResourceManager.GetObject("verydarkwall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap walter {
            get {
                object obj = ResourceManager.GetObject("walter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercooler {
            get {
                object obj = ResourceManager.GetObject("watercooler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercoolerEmpty {
            get {
                object obj = ResourceManager.GetObject("watercoolerEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wayBetterWires {
            get {
                object obj = ResourceManager.GetObject("wayBetterWires", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet collected the grand sum of ${0:F2} demanded of you by the snack gods..
        /// </summary>
        internal static string WinCondt_No {
            get {
                return ResourceManager.GetString("WinCondt_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a mighty crusade and the massacre of your company&apos;s entire workforce, you have finally scrounged up enough change to appease the snack gods.
        ///
        ///In return, they have granted you, from the divine locale of B2, a fun-sized pouch of assorted hard pretzles.
        ///
        ///May you go forth from this sacred shrine with your hunger satiated, ready to be productive for your recently departed boss..
        /// </summary>
        internal static string WinCondt_Yes {
            get {
                return ResourceManager.GetString("WinCondt_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood {
            get {
                object obj = ResourceManager.GetObject("wood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
