//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dummy {
            get {
                object obj = ResourceManager.GetObject("dummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fancydoor {
            get {
                object obj = ResourceManager.GetObject("fancydoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Heroes&gt;
        ///  &lt;Hero id=&quot;1&quot; texture=&quot;milton&quot; name=&quot;Milton&quot;&gt;
        ///	&lt;Attributes stamina=&quot;14&quot; strength=&quot;14&quot; intellect=&quot;8&quot; dexterity=&quot;9&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot;/&gt;
        ///	&lt;Item id=&quot;2&quot;/&gt;
        ///	&lt;Item id=&quot;3&quot;/&gt;
        ///	&lt;Item id=&quot;4&quot;/&gt;
        ///	&lt;Item id=&quot;5&quot;/&gt;
        ///	&lt;Spell id=&quot;1&quot;/&gt;
        ///	&lt;Spell id=&quot;2&quot;/&gt;
        ///	&lt;Spell id=&quot;3&quot;/&gt;
        ///  &lt;/Hero&gt;
        ///  &lt;Hero id=&quot;2&quot; texture=&quot;stu&quot; name=&quot;Stu Steiner&quot;&gt;
        ///	&lt;Attributes stamina=&quot;11&quot; strength=&quot;12&quot; intellect=&quot;15&quot; dexterity=&quot;7&quot;/&gt;
        ///	&lt;Spell id=&quot;1&quot;/&gt;
        ///	&lt;Spell id=&quot;2&quot;/&gt;
        ///  &lt;/Hero&gt;
        ///&lt;/Heroes&gt;
        ///.
        /// </summary>
        internal static string Heroes {
            get {
                return ResourceManager.GetString("Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///  &lt;!--SlotIDs:
        ///	  Weapon,
        ///	  Head,
        ///	  Body,
        ///	  Hands,
        ///	  Feet,
        ///  --&gt;
        ///  &lt;Equippable id=&quot;1&quot; name=&quot;Amazing Body&quot; slot=&quot;Body&quot;&gt;
        ///	&lt;Attributes stamina=&quot;100&quot; strength=&quot;100&quot; intellect=&quot;100&quot; dexterity=&quot;100&quot;/&gt;
        ///  &lt;/Equippable&gt;
        ///  &lt;Equippable id=&quot;2&quot; name=&quot;Amazing Hat&quot; slot=&quot;Head&quot;&gt;
        ///	&lt;Attributes stamina=&quot;100&quot; strength=&quot;100&quot; intellect=&quot;100&quot; dexterity=&quot;100&quot;/&gt;
        ///  &lt;/Equippable&gt;
        ///  &lt;Equippable id=&quot;3&quot; name=&quot;Amazing Gloves&quot; slot=&quot;Hands&quot;&gt;
        ///	&lt;Attributes stamina=&quot;100&quot; stre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;LootPools&gt;
        ///  &lt;LootPool id=&quot;1&quot;&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;1&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;5&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;4&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;3&quot; chance=&quot;1.0&quot;/&gt;
        ///	&lt;Item id=&quot;2&quot; chance=&quot;.5&quot;/&gt;
        ///  &lt;Item id =&quot;100&quot; chance=&quot;1&quot;/&gt;
        ///  &lt;/LootPool&gt;
        ///&lt;/LootPools&gt;.
        /// </summary>
        internal static string LootPools {
            get {
                return ResourceManager.GetString("LootPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lumbergh {
            get {
                object obj = ResourceManager.GetObject("lumbergh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Maps&gt;
        ///  &lt;Map id=&quot;1&quot;&gt;
        ///	&lt;Tiles&gt;
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 01 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 00 00 00 00 00 00 00
        ///	  00 00 00 00 00 00 00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap milton {
            get {
                object obj = ResourceManager.GetObject("milton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Monsters&gt;
        ///  &lt;Monster id=&quot;1&quot; texture=&quot;lumbergh&quot; name=&quot;Boss&quot;&gt;
        ///	&lt;Attributes stamina=&quot;10&quot; strength=&quot;11&quot; intellect=&quot;8&quot; dexterity=&quot;15&quot;/&gt;
        ///	&lt;Spell id=&quot;2&quot;/&gt;
        ///	&lt;Spell id=&quot;2&quot;/&gt;
        ///	&lt;Spell id=&quot;1&quot;/&gt;
        ///	&lt;LootPool id=&quot;1&quot;/&gt;
        ///  &lt;/Monster&gt;
        ///  &lt;Monster id=&quot;2&quot; texture=&quot;shoerner&quot; name=&quot;Pestering Student&quot;&gt;
        ///	&lt;Attributes stamina=&quot;8&quot; strength=&quot;9&quot; intellect=&quot;16&quot; dexterity=&quot;9&quot;/&gt;
        ///	&lt;Spell id=&quot;1&quot;/&gt;
        ///  &lt;/Monster&gt;
        ///  
        ///  &lt;Monster id=&quot;3&quot; texture=&quot;dummy&quot; name=&quot;Dummy&quot;&gt;
        ///	&lt;Attributes stamina=&quot;999999 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shoerner {
            get {
                object obj = ResourceManager.GetObject("shoerner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Spells&gt;
        ///  &lt;TargetedDamage name=&quot;Basic Spell&quot; id=&quot;1&quot; damage=&quot;5&quot; castTime=&quot;2&quot; cooldown=&quot;0&quot;/&gt;
        ///  &lt;TargetedDamage name=&quot;DOOOOOOMMMM&quot; id=&quot;2&quot; damage=&quot;150&quot; castTime=&quot;3&quot; cooldown=&quot;5&quot;/&gt;
        ///  &lt;TargetedDamage name=&quot;Rapid Fire&quot; id=&quot;3&quot; damage=&quot;3&quot; castTime=&quot;0.1&quot; cooldown=&quot;0&quot;/&gt;
        ///&lt;/Spells&gt;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stu {
            get {
                object obj = ResourceManager.GetObject("stu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Tiles&gt;
        ///  &lt;Tile id=&quot;0&quot; texture=&quot;&quot; obstacle=&quot;false&quot;/&gt;
        ///  &lt;Tile id=&quot;1&quot; texture=&quot;lumbergh&quot; obstacle=&quot;false&quot;/&gt;
        ///  &lt;Tile id=&quot;2&quot; texture=&quot;shoerner&quot; obstacle=&quot;true&quot;/&gt;
        ///&lt;/Tiles&gt;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood {
            get {
                object obj = ResourceManager.GetObject("wood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
