//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black {
            get {
                object obj = ResourceManager.GetObject("black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bug {
            get {
                object obj = ResourceManager.GetObject("bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cables {
            get {
                object obj = ResourceManager.GetObject("cables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carpet {
            get {
                object obj = ResourceManager.GetObject("carpet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap carty {
            get {
                object obj = ResourceManager.GetObject("carty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap darktile {
            get {
                object obj = ResourceManager.GetObject("darktile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap darkwall {
            get {
                object obj = ResourceManager.GetObject("darkwall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desk {
            get {
                object obj = ResourceManager.GetObject("desk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deskdark {
            get {
                object obj = ResourceManager.GetObject("deskdark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deskevil {
            get {
                object obj = ResourceManager.GetObject("deskevil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deskmed {
            get {
                object obj = ResourceManager.GetObject("deskmed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dummy {
            get {
                object obj = ResourceManager.GetObject("dummy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elevatorDown {
            get {
                object obj = ResourceManager.GetObject("elevatorDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elevatorUp {
            get {
                object obj = ResourceManager.GetObject("elevatorUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fancydoor {
            get {
                object obj = ResourceManager.GetObject("fancydoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Heroes&gt;
        ///  &lt;Hero id=&quot;1&quot; texture=&quot;milton&quot; name=&quot;Milton&quot;
        ///		desc=&quot;A master of the incendiary arts, Milton&apos;s talents are oft overlooked due to his poor communication skills and affinity for staplers of the red Swingline variety.&quot;&gt;
        ///	&lt;Attributes stamina=&quot;14&quot; block =&quot;60&quot; combo =&quot;10&quot;/&gt;
        ///	&lt;Item id=&quot;11&quot;/&gt;
        ///	&lt;Item id=&quot;15&quot;/&gt;
        ///	&lt;Item id=&quot;16&quot;/&gt;
        ///	&lt;Item id=&quot;17&quot;/&gt;
        ///	
        ///	&lt;Spell id=&quot;1&quot;/&gt;
        ///	&lt;Spell id=&quot;2&quot;/&gt;
        ///	&lt;Spell id=&quot;3&quot;/&gt;
        ///  &lt;/Hero&gt;
        ///  &lt;Hero id=&quot;2&quot; texture=&quot;stu&quot; name=&quot;Stu Steiner&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heroes {
            get {
                return ResourceManager.GetString("Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///  &lt;!--SlotIDs:
        ///	  Weapon,
        ///	  Head,
        ///	  Body,
        ///	  Feet,
        ///  --&gt;
        ///  &lt;Equippable id=&quot;1&quot; name=&quot;Amazing Body&quot; slot=&quot;Body&quot;&gt;
        ///    &lt;Attributes stamina=&quot;100&quot; block =&quot;100&quot; combo =&quot;100&quot;/&gt;
        ///  &lt;/Equippable&gt;
        ///  &lt;Equippable id=&quot;2&quot; name=&quot;Amazing Hat&quot; slot=&quot;Head&quot;&gt;
        ///    &lt;Attributes stamina=&quot;100&quot; block =&quot;100&quot; combo =&quot;100&quot;/&gt;
        ///  &lt;/Equippable&gt;
        ///  &lt;Equippable id=&quot;3&quot; name=&quot;Amazing Gloves&quot; slot=&quot;Hands&quot;&gt;
        ///    &lt;Attributes stamina=&quot;100&quot; block =&quot;100&quot; combo =&quot;100&quot;/&gt;
        ///  &lt;/Equippable&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;LootPools&gt;
        ///  &lt;LootPool id=&quot;1&quot;&gt;
        ///	&lt;Item id=&quot;11&quot; chance=&quot;0.2&quot;/&gt;
        ///	&lt;Item id=&quot;12&quot; chance=&quot;0.2&quot;/&gt;
        ///	&lt;Item id=&quot;14&quot; chance=&quot;0.2&quot;/&gt;
        ///	&lt;Item id=&quot;15&quot; chance=&quot;0.2&quot;/&gt;
        ///	&lt;Item id=&quot;16&quot; chance=&quot;0.2&quot;/&gt;
        ///	&lt;Item id=&quot;17&quot; chance=&quot;0.2&quot;/&gt;
        ///  &lt;Item id=&quot;203&quot; chance=&quot;1&quot;/&gt;
        ///
        ///	&lt;Item id=&quot;101&quot; chance=&quot;0.7&quot;/&gt;
        ///	&lt;Item id=&quot;101&quot; chance=&quot;0.7&quot;/&gt;
        ///  &lt;/LootPool&gt;
        ///  
        ///  &lt;LootPool id=&quot;2&quot;&gt;
        ///	&lt;Item id=&quot;11&quot; chance=&quot;0.9&quot;/&gt;
        ///	&lt;Item id=&quot;14&quot; chance=&quot;0.9&quot;/&gt;
        ///  &lt;/LootPool&gt;
        ///&lt;/LootPools&gt;.
        /// </summary>
        internal static string LootPools {
            get {
                return ResourceManager.GetString("LootPools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lumbergh {
            get {
                object obj = ResourceManager.GetObject("lumbergh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Maps&gt;
        ///  &lt;Map id=&quot;1&quot;&gt;
        ///	&lt;Tiles&gt;
        ///	  02 02 02 02 02 02 02 02 02 02 02 02 02
        ///	  02 00 02 03 00 00 00 04 02 04 00 00 02
        ///	  02 00 02 00 00 00 00 00 02 00 00 00 02
        ///	  02 00 02 00 00 00 00 00 02 02 00 02 02
        ///	  02 00 00 00 00 00 00 00 00 00 00 00 02
        ///	  02 00 00 00 00 00 00 00 00 00 00 00 02
        ///	  02 00 00 00 00 00 00 00 00 00 00 00 02
        ///	  02 03 00 00 00 00 00 00 00 00 00 00 02
        ///	  02 02 02 02 00 00 00 00 00 00 00 00 02
        ///	  02 20 00 02 00 00 00 00 00 00 00 00 02
        ///	  02 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medbox {
            get {
                object obj = ResourceManager.GetObject("medbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medtile {
            get {
                object obj = ResourceManager.GetObject("medtile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap milton {
            get {
                object obj = ResourceManager.GetObject("milton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Monsters&gt;
        ///
        ///  &lt;Monster id=&quot;3&quot; texture=&quot;dummy&quot; name=&quot;Dummy&quot;&gt;
        ///	&lt;Attributes stamina=&quot;9999999&quot; block =&quot;10&quot; combo =&quot;10&quot;/&gt;
        ///  &lt;/Monster&gt;
        ///  
        ///  
        ///  
        ///  &lt;Monster id=&quot;1&quot; texture=&quot;lumbergh&quot; name=&quot;Boss&quot;&gt;
        ///	&lt;Attributes stamina=&quot;10&quot; block=&quot;10&quot; combo=&quot;10&quot;/&gt;
        ///	&lt;Spell id=&quot;22&quot;/&gt;
        ///	&lt;Spell id=&quot;21&quot;/&gt;
        ///	&lt;LootPool id=&quot;1&quot;/&gt;
        ///  &lt;/Monster&gt;
        ///  &lt;Monster id=&quot;2&quot; texture=&quot;shoerner&quot; name=&quot;Pestering Student&quot;&gt;
        ///	&lt;Attributes stamina=&quot;8&quot; block=&quot;10&quot; combo=&quot;10&quot;/&gt;
        ///	&lt;Spell id=&quot;31&quot;/&gt;
        ///	&lt;Spell id=&quot;32&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Monsters {
            get {
                return ResourceManager.GetString("Monsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plant1 {
            get {
                object obj = ResourceManager.GetObject("plant1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plant2 {
            get {
                object obj = ResourceManager.GetObject("plant2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap serverBase {
            get {
                object obj = ResourceManager.GetObject("serverBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap serverLights {
            get {
                object obj = ResourceManager.GetObject("serverLights", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap serverRed {
            get {
                object obj = ResourceManager.GetObject("serverRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shoerner {
            get {
                object obj = ResourceManager.GetObject("shoerner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smallbox {
            get {
                object obj = ResourceManager.GetObject("smallbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Spells&gt;
        ///  &lt;!--Milton--&gt;
        ///  &lt;TargetedDamage id=&quot;1&quot; name=&quot;Mumble&quot; damage=&quot;9&quot; castTime=&quot;2&quot; cooldown=&quot;6&quot;/&gt;
        ///  &lt;TargetedDamage id=&quot;2&quot; name=&quot;Staple Fire&quot; damage=&quot;1&quot; castTime=&quot;0.3&quot; cooldown=&quot;0&quot;/&gt;
        ///  &lt;AreaDamage	  id=&quot;3&quot; name=&quot;Incinerate&quot; damage=&quot;20&quot; castTime=&quot;2.5&quot; cooldown=&quot;10&quot;/&gt;
        ///  
        ///  &lt;!--Stu--&gt;
        ///  &lt;TargetedDamage id=&quot;11&quot; name=&quot;Booming Voice&quot; damage=&quot;6&quot; castTime=&quot;3&quot; cooldown=&quot;0&quot;/&gt;
        ///  &lt;AreaDamage	  id=&quot;12&quot; name=&quot;Knowledge Blast&quot; damage=&quot;18&quot; castTime=&quot;4&quot; cooldown=&quot;8&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stu {
            get {
                object obj = ResourceManager.GetObject("stu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Tiles&gt;
        ///  &lt;Tile id=&quot;0&quot; texture=&quot;carpet&quot; obstacle=&quot;false&quot;/&gt;
        ///  &lt;Tile id=&quot;1&quot; texture=&quot;lumbergh&quot; obstacle=&quot;false&quot;/&gt;
        ///  &lt;Tile id=&quot;2&quot; texture=&quot;wall&quot; obstacle=&quot;true&quot;/&gt;
        ///  &lt;Tile id=&quot;3&quot; texture=&quot;carpet plant1&quot; obstacle=&quot;true&quot;/&gt;
        ///  &lt;Tile id=&quot;4&quot; texture=&quot;carpet deskmed&quot; obstacle=&quot;true&quot;/&gt;
        ///  &lt;Tile id=&quot;5&quot; texture=&quot;carpet plant2&quot; obstacle=&quot;true&quot;/&gt;
        ///  &lt;Object id=&quot;20&quot; texture=&quot;darktile&quot; object=&quot;Server&quot;/&gt;
        ///  &lt;Tile id=&quot;21&quot; texture=&quot;verydarkwall&quot; obstacle=&quot;true&quot;/&gt;
        ///  &lt;Tile id=&quot;22&quot; te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap verydarkwall {
            get {
                object obj = ResourceManager.GetObject("verydarkwall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercooler {
            get {
                object obj = ResourceManager.GetObject("watercooler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercoolerEmpty {
            get {
                object obj = ResourceManager.GetObject("watercoolerEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood {
            get {
                object obj = ResourceManager.GetObject("wood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
